<a href="https://colab.research.google.com/github/RadhikaNir/Machine-Learning-1633/blob/main/Market_Basket_Analysis_Association_Rule_MBA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Market Basket Analysis

In [1]:
pip install apyori

Requirement already satisfied: apyori in /usr/local/lib/python3.13/dist-packages (1.1.2)

In [2]:
## Load the data
import pandas as pd
path = r"https://raw.githubusercontent.com/RadhikaNir/Datasets/refs/heads/main/store_data.csv"
df = pd.read_csv(path,header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Generate a nested list where each sub list contains complete row information

example : [[shrimp,burgers
chutney
turkey
mineral water
low fat yogurt
whole wheat pasta
soup
frozen vegetables
french fries
eggs
cookies
turkey
spaghetti
mineral water
mineral water
shrimp
turkey
turkey
meatballs],
[meatballs,eggs],
[pasta]]

In [3]:
df.shape

(7501, 20)

In [4]:
rows = df.shape[0]
cols = df.shape[1]

In [5]:
df.values[0][0]

'shrimp'

In [6]:
[str(df.values[0,j]) for j in range(cols)]
# df.values[0,0],df.values[0,1],df.values[0,2]....df.values[0,19] 1st row
# df.values[1,0],df.values[1,1],df.values[1,2]....df.values[1,19] 2nd row

['shrimp',
 'almonds',
 'avocado',
 'vegetables mix',
 'green grapes',
 'whole weat flour',
 'yams',
 'cottage cheese',
 'energy drink',
 'tomato juice',
 'low fat yogurt',
 'green tea',
 'honey',
 'salad',
 'mineral water',
 'salmon',
 'antioxydant juice',
 'frozen smoothie',
 'spinach',
 'olive oil']

In [7]:
records = []
for i in range(rows):
  records.append([str(df.values[i,j]) for j in range(cols)])
print(records[:10])

[['shrimp', 'almonds', 'avocado', 'vegetables mix', 'green grapes', 'whole weat flour', 'yams', 'cottage cheese', 'energy drink', 'tomato juice', 'low fat yogurt', 'green tea', 'honey', 'salad', 'mineral water', 'salmon', 'antioxydant juice', 'frozen smoothie', 'spinach', 'olive oil'], ['burgers', 'meatballs', 'eggs', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'], ['chutney', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'], ['turkey', 'avocado', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'], ['mineral water', 'milk', 'energy bar', 'whole wheat rice', 'green tea', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'], ['low fat yogurt', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'], ['whole wheat pasta', 'french fries', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'], ['soup', 'light cream', 'shallot', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'], ['frozen vegetables', 'spaghetti', 'green tea', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan'], ['french fries', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan', 'nan']]

In [8]:
rows

7501

## To build the association rules, we need to build the criteria*

support : based on data
confidence : 0.2
lift : 3

support : transactions - weekly data: 7days , 5
support : 7*5/total transactions  = 35/7500

In [9]:
35/len(df)

0.004666044527396347

In [10]:
from apyori import apriori
sup = 7*5/len(df)
conf = 0.2
lift = 3

association_rules = apriori(records,min_support=sup,min_confidence=conf,min_lift=lift)
association_rules = list(association_rules)
print(association_rules[:10])

[RelationRecord(items=frozenset({'escalope', 'mushroom cream sauce'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]), RelationRecord(items=frozenset({'escalope', 'pasta'}), support=0.005865884548726837, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794)]), RelationRecord(items=frozenset({'herb & pepper', 'ground beef'}), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2919938411349285)]), RelationRecord(items=frozenset({'tomato sauce', 'ground beef'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.3773584905660377, lift=3.840659481324083)]), RelationRecord(items=frozenset({'whole wheat pasta', 'olive oil'}), support=0.007998933475536596, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.122410097642296)]), RelationRecord(items=frozenset({'pasta', 'shrimp'}), support=0.005065991201173177, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050847, lift=4.506672147735896)]), RelationRecord(items=frozenset({'frozen vegetables', 'shrimp', 'chocolate'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'frozen vegetables', 'chocolate'}), items_add=frozenset({'shrimp'}), confidence=0.23255813953488375, lift=3.2545123221103784), OrderedStatistic(items_base=frozenset({'shrimp', 'chocolate'}), items_add=frozenset({'frozen vegetables'}), confidence=0.29629629629629634, lift=3.1084175084175087)]), RelationRecord(items=frozenset({'spaghetti', 'cooking oil', 'ground beef'}), support=0.004799360085321957, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cooking oil', 'ground beef'}), items_add=frozenset({'spaghetti'}), confidence=0.5714285714285714, lift=3.2819951870487856), OrderedStatistic(items_base=frozenset({'spaghetti', 'cooking oil'}), items_add=frozenset({'ground beef'}), confidence=0.3025210084033613, lift=3.0789824749438446)]), RelationRecord(items=frozenset({'escalope', 'nan', 'mushroom cream sauce'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope', 'nan'}), confidence=0.3006993006993007, lift=3.790832696715049), OrderedStatistic(items_base=frozenset({'nan', 'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]), RelationRecord(items=frozenset({'escalope', 'pasta', 'nan'}), support=0.005865884548726837, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope', 'nan'}), confidence=0.3728813559322034, lift=4.700811850163794), OrderedStatistic(items_base=frozenset({'pasta', 'nan'}), items_add=frozenset({'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794)])]

In [11]:
len(association_rules)

44

In [12]:
association_rules[0]

RelationRecord(items=frozenset({'escalope', 'mushroom cream sauce'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)])

In [13]:
association_rules[0][0]

frozenset({'escalope', 'mushroom cream sauce'})

In [14]:
association_products = []
for i in association_rules[0][0]:
  association_products.append(i)
print(association_products)

['escalope', 'mushroom cream sauce']

In [16]:
support = association_rules[0][1]
support

0.005732568990801226

In [17]:
association_rules[0][2]

[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]

In [18]:
association_rules[0][2][0]

OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)

In [19]:
print(association_rules[0][2][0][2])
print(association_rules[0][2][0][3])

0.3006993006993007
3.790832696715049

In [20]:
results = []
for items in association_rules:
  # Extract product associations
  item_pair = items[0] # frozen set of items
  item_data = [i for i in item_pair] # save the items in a list

  support1 = items[1] # Support

  confidence1 = items[2][0][2]
  lift1 = items[2][0][3]

  results.append([item_data,round(support1,3),round(confidence1,3),round(lift1,2)])
  print(results)

[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta', 'nan'], 0.006, 0.373, 4.7]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta', 'nan'], 0.006, 0.373, 4.7], [['spaghetti', 'frozen vegetables', 'ground beef'], 0.009, 0.311, 3.17]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta', 'nan'], 0.006, 0.373, 4.7], [['spaghetti', 'frozen vegetables', 'ground beef'], 0.009, 0.311, 3.17], [['frozen vegetables', 'milk', 'olive oil'], 0.005, 0.203, 3.09]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta', 'nan'], 0.006, 0.373, 4.7], [['spaghetti', 'frozen vegetables', 'ground beef'], 0.009, 0.311, 3.17], [['frozen vegetables', 'milk', 'olive oil'], 0.005, 0.203, 3.09], [['mineral water', 'frozen vegetables', 'shrimp'], 0.007, 0.305, 3.2]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta', 'nan'], 0.006, 0.373, 4.7], [['spaghetti', 'frozen vegetables', 'ground beef'], 0.009, 0.311, 3.17], [['frozen vegetables', 'milk', 'olive oil'], 0.005, 0.203, 3.09], [['mineral water', 'frozen vegetables', 'shrimp'], 0.007, 0.305, 3.2], [['spaghetti', 'frozen vegetables', 'olive oil'], 0.006, 0.206, 3.12]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta', 'nan'], 0.006, 0.373, 4.7], [['spaghetti', 'frozen vegetables', 'ground beef'], 0.009, 0.311, 3.17], [['frozen vegetables', 'milk', 'olive oil'], 0.005, 0.203, 3.09], [['mineral water', 'frozen vegetables', 'shrimp'], 0.007, 0.305, 3.2], [['spaghetti', 'frozen vegetables', 'olive oil'], 0.006, 0.206, 3.12], [['spaghetti', 'frozen vegetables', 'shrimp'], 0.006, 0.215, 3.01]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta', 'nan'], 0.006, 0.373, 4.7], [['spaghetti', 'frozen vegetables', 'ground beef'], 0.009, 0.311, 3.17], [['frozen vegetables', 'milk', 'olive oil'], 0.005, 0.203, 3.09], [['mineral water', 'frozen vegetables', 'shrimp'], 0.007, 0.305, 3.2], [['spaghetti', 'frozen vegetables', 'olive oil'], 0.006, 0.206, 3.12], [['spaghetti', 'frozen vegetables', 'shrimp'], 0.006, 0.215, 3.01], [['spaghetti', 'tomatoes', 'frozen vegetables'], 0.007, 0.239, 3.5]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta', 'nan'], 0.006, 0.373, 4.7], [['spaghetti', 'frozen vegetables', 'ground beef'], 0.009, 0.311, 3.17], [['frozen vegetables', 'milk', 'olive oil'], 0.005, 0.203, 3.09], [['mineral water', 'frozen vegetables', 'shrimp'], 0.007, 0.305, 3.2], [['spaghetti', 'frozen vegetables', 'olive oil'], 0.006, 0.206, 3.12], [['spaghetti', 'frozen vegetables', 'shrimp'], 0.006, 0.215, 3.01], [['spaghetti', 'tomatoes', 'frozen vegetables'], 0.007, 0.239, 3.5], [['spaghetti', 'ground beef', 'grated cheese'], 0.005, 0.323, 3.28]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta', 'nan'], 0.006, 0.373, 4.7], [['spaghetti', 'frozen vegetables', 'ground beef'], 0.009, 0.311, 3.17], [['frozen vegetables', 'milk', 'olive oil'], 0.005, 0.203, 3.09], [['mineral water', 'frozen vegetables', 'shrimp'], 0.007, 0.305, 3.2], [['spaghetti', 'frozen vegetables', 'olive oil'], 0.006, 0.206, 3.12], [['spaghetti', 'frozen vegetables', 'shrimp'], 0.006, 0.215, 3.01], [['spaghetti', 'tomatoes', 'frozen vegetables'], 0.007, 0.239, 3.5], [['spaghetti', 'ground beef', 'grated cheese'], 0.005, 0.323, 3.28], [['herb & pepper', 'mineral water', 'ground beef'], 0.007, 0.391, 3.98]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta', 'nan'], 0.006, 0.373, 4.7], [['spaghetti', 'frozen vegetables', 'ground beef'], 0.009, 0.311, 3.17], [['frozen vegetables', 'milk', 'olive oil'], 0.005, 0.203, 3.09], [['mineral water', 'frozen vegetables', 'shrimp'], 0.007, 0.305, 3.2], [['spaghetti', 'frozen vegetables', 'olive oil'], 0.006, 0.206, 3.12], [['spaghetti', 'frozen vegetables', 'shrimp'], 0.006, 0.215, 3.01], [['spaghetti', 'tomatoes', 'frozen vegetables'], 0.007, 0.239, 3.5], [['spaghetti', 'ground beef', 'grated cheese'], 0.005, 0.323, 3.28], [['herb & pepper', 'mineral water', 'ground beef'], 0.007, 0.391, 3.98], [['herb & pepper', 'nan', 'ground beef'], 0.016, 0.323, 3.29]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta', 'nan'], 0.006, 0.373, 4.7], [['spaghetti', 'frozen vegetables', 'ground beef'], 0.009, 0.311, 3.17], [['frozen vegetables', 'milk', 'olive oil'], 0.005, 0.203, 3.09], [['mineral water', 'frozen vegetables', 'shrimp'], 0.007, 0.305, 3.2], [['spaghetti', 'frozen vegetables', 'olive oil'], 0.006, 0.206, 3.12], [['spaghetti', 'frozen vegetables', 'shrimp'], 0.006, 0.215, 3.01], [['spaghetti', 'tomatoes', 'frozen vegetables'], 0.007, 0.239, 3.5], [['spaghetti', 'ground beef', 'grated cheese'], 0.005, 0.323, 3.28], [['herb & pepper', 'mineral water', 'ground beef'], 0.007, 0.391, 3.98], [['herb & pepper', 'nan', 'ground beef'], 0.016, 0.323, 3.29], [['herb & pepper', 'spaghetti', 'ground beef'], 0.006, 0.393, 4.0]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta', 'nan'], 0.006, 0.373, 4.7], [['spaghetti', 'frozen vegetables', 'ground beef'], 0.009, 0.311, 3.17], [['frozen vegetables', 'milk', 'olive oil'], 0.005, 0.203, 3.09], [['mineral water', 'frozen vegetables', 'shrimp'], 0.007, 0.305, 3.2], [['spaghetti', 'frozen vegetables', 'olive oil'], 0.006, 0.206, 3.12], [['spaghetti', 'frozen vegetables', 'shrimp'], 0.006, 0.215, 3.01], [['spaghetti', 'tomatoes', 'frozen vegetables'], 0.007, 0.239, 3.5], [['spaghetti', 'ground beef', 'grated cheese'], 0.005, 0.323, 3.28], [['herb & pepper', 'mineral water', 'ground beef'], 0.007, 0.391, 3.98], [['herb & pepper', 'nan', 'ground beef'], 0.016, 0.323, 3.29], [['herb & pepper', 'spaghetti', 'ground beef'], 0.006, 0.393, 4.0], [['olive oil', 'milk', 'ground beef'], 0.005, 0.224, 3.4]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta', 'nan'], 0.006, 0.373, 4.7], [['spaghetti', 'frozen vegetables', 'ground beef'], 0.009, 0.311, 3.17], [['frozen vegetables', 'milk', 'olive oil'], 0.005, 0.203, 3.09], [['mineral water', 'frozen vegetables', 'shrimp'], 0.007, 0.305, 3.2], [['spaghetti', 'frozen vegetables', 'olive oil'], 0.006, 0.206, 3.12], [['spaghetti', 'frozen vegetables', 'shrimp'], 0.006, 0.215, 3.01], [['spaghetti', 'tomatoes', 'frozen vegetables'], 0.007, 0.239, 3.5], [['spaghetti', 'ground beef', 'grated cheese'], 0.005, 0.323, 3.28], [['herb & pepper', 'mineral water', 'ground beef'], 0.007, 0.391, 3.98], [['herb & pepper', 'nan', 'ground beef'], 0.016, 0.323, 3.29], [['herb & pepper', 'spaghetti', 'ground beef'], 0.006, 0.393, 4.0], [['olive oil', 'milk', 'ground beef'], 0.005, 0.224, 3.4], [['tomato sauce', 'nan', 'ground beef'], 0.005, 0.377, 3.84]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta', 'nan'], 0.006, 0.373, 4.7], [['spaghetti', 'frozen vegetables', 'ground beef'], 0.009, 0.311, 3.17], [['frozen vegetables', 'milk', 'olive oil'], 0.005, 0.203, 3.09], [['mineral water', 'frozen vegetables', 'shrimp'], 0.007, 0.305, 3.2], [['spaghetti', 'frozen vegetables', 'olive oil'], 0.006, 0.206, 3.12], [['spaghetti', 'frozen vegetables', 'shrimp'], 0.006, 0.215, 3.01], [['spaghetti', 'tomatoes', 'frozen vegetables'], 0.007, 0.239, 3.5], [['spaghetti', 'ground beef', 'grated cheese'], 0.005, 0.323, 3.28], [['herb & pepper', 'mineral water', 'ground beef'], 0.007, 0.391, 3.98], [['herb & pepper', 'nan', 'ground beef'], 0.016, 0.323, 3.29], [['herb & pepper', 'spaghetti', 'ground beef'], 0.006, 0.393, 4.0], [['olive oil', 'milk', 'ground beef'], 0.005, 0.224, 3.4], [['tomato sauce', 'nan', 'ground beef'], 0.005, 0.377, 3.84], [['spaghetti', 'shrimp', 'ground beef'], 0.006, 0.523, 3.01]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta', 'nan'], 0.006, 0.373, 4.7], [['spaghetti', 'frozen vegetables', 'ground beef'], 0.009, 0.311, 3.17], [['frozen vegetables', 'milk', 'olive oil'], 0.005, 0.203, 3.09], [['mineral water', 'frozen vegetables', 'shrimp'], 0.007, 0.305, 3.2], [['spaghetti', 'frozen vegetables', 'olive oil'], 0.006, 0.206, 3.12], [['spaghetti', 'frozen vegetables', 'shrimp'], 0.006, 0.215, 3.01], [['spaghetti', 'tomatoes', 'frozen vegetables'], 0.007, 0.239, 3.5], [['spaghetti', 'ground beef', 'grated cheese'], 0.005, 0.323, 3.28], [['herb & pepper', 'mineral water', 'ground beef'], 0.007, 0.391, 3.98], [['herb & pepper', 'nan', 'ground beef'], 0.016, 0.323, 3.29], [['herb & pepper', 'spaghetti', 'ground beef'], 0.006, 0.393, 4.0], [['olive oil', 'milk', 'ground beef'], 0.005, 0.224, 3.4], [['tomato sauce', 'nan', 'ground beef'], 0.005, 0.377, 3.84], [['spaghetti', 'shrimp', 'ground beef'], 0.006, 0.523, 3.01], [['spaghetti', 'milk', 'olive oil'], 0.007, 0.203, 3.08]]
[[['escalope', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta'], 0.006, 0.373, 4.7], [['herb & pepper', 'ground beef'], 0.016, 0.323, 3.29], [['tomato sauce', 'ground beef'], 0.005, 0.377, 3.84], [['whole wheat pasta', 'olive oil'], 0.008, 0.271, 4.12], [['pasta', 'shrimp'], 0.005, 0.322, 4.51], [['frozen vegetables', 'shrimp', 'chocolate'], 0.005, 0.233, 3.25], [['spaghetti', 'cooking oil', 'ground beef'], 0.005, 0.571, 3.28], [['escalope', 'nan', 'mushroom cream sauce'], 0.006, 0.301, 3.79], [['escalope', 'pasta', 'nan'], 0.006, 0.373, 4.7], [['spaghetti', 'frozen vegetables', 'ground beef'], 0.009, 0.311, 3.17], [['frozen vegetables', 'milk', 'olive oil'], 0.005, 0.203, 3.09], [['mineral water', 'frozen vegetables', 'shrimp'], 0.007, 0.305, 3.2], [['spaghetti', 'frozen vegetables', 'olive oil'], 0.006, 0.206, 3.12], [['spaghetti', 'frozen vegetables', 'shrimp'], 0.006, 0.215, 3.01], [['spaghetti', 'tomatoes', 'frozen vegetables'], 0.007, 0.239, 3.5], [['spaghetti', 'ground beef', 'grated cheese'], 0.005, 0.323, 3.28], [['herb & pepper', 'mineral water', 'ground beef'], 0.007, 0.391, 3.98], [['herb & pepper', 'nan', 'ground beef'], 0.016, 0.323, 3.29], [['herb & pepper', 'spaghetti', 'ground beef'], 0.006, 0.393, 4.0], [['olive oil', 'milk', 'ground beef'], 0.005, 0.224, 3.4], [['tomato sauce', 'nan', 'ground beef'], 0.005, 0.377, 3.84], [['spaghetti', 'shrimp', 'ground beef'], 0.006, 0.523, 3.01], [['spaghetti', 'milk', 'olive oil'], 0.007, 0.203, 3.08], [['soup', 'mineral water', 'olive oil'], 0.005, 0.225, 3.42]]

In [21]:
## Save these results inside a dataframe and share with the client
df_results = pd.DataFrame(results)
df_results

                                                   0      1      2     3
0                   [escalope, mushroom cream sauce]  0.006  0.301  3.79
1                                  [escalope, pasta]  0.006  0.373  4.70
2                       [herb & pepper, ground beef]  0.016  0.323  3.29
3                        [tomato sauce, ground beef]  0.005  0.377  3.84
4                     [whole wheat pasta, olive oil]  0.008  0.271  4.12
5                                    [pasta, shrimp]  0.005  0.322  4.51
6             [frozen vegetables, shrimp, chocolate]  0.005  0.233  3.25
7              [spaghetti, cooking oil, ground beef]  0.005  0.571  3.28
8              [escalope, nan, mushroom cream sauce]  0.006  0.301  3.79
9                             [escalope, pasta, nan]  0.006  0.373  4.70
10       [spaghetti, frozen vegetables, ground beef]  0.009  0.311  3.17
11              [frozen vegetables, milk, olive oil]  0.005  0.203  3.09
12        [mineral water, frozen vegetables, shrimp]  0.007  0.305  3.20
13         [spaghetti, frozen vegetables, olive oil]  0.006  0.206  3.12
14            [spaghetti, frozen vegetables, shrimp]  0.006  0.215  3.01
15          [spaghetti, tomatoes, frozen vegetables]  0.007  0.239  3.50
16           [spaghetti, ground beef, grated cheese]  0.005  0.323  3.28
17       [herb & pepper, mineral water, ground beef]  0.007  0.391  3.98
18                 [herb & pepper, nan, ground beef]  0.016  0.323  3.29
19           [herb & pepper, spaghetti, ground beef]  0.006  0.393  4.00
20                    [olive oil, milk, ground beef]  0.005  0.224  3.40
21                  [tomato sauce, nan, ground beef]  0.005  0.377  3.84
22                  [spaghetti, shrimp, ground beef]  0.006  0.523  3.01
23                      [spaghetti, milk, olive oil]  0.007  0.203  3.08
24                  [soup, mineral water, olive oil]  0.005  0.225  3.42
25               [nan, whole wheat pasta, olive oil]  0.008  0.271  4.13
26                              [pasta, nan, shrimp]  0.005  0.322  4.52
27                  [spaghetti, pancakes, olive oil]  0.005  0.201  3.05
28       [nan, frozen vegetables, shrimp, chocolate]  0.005  0.233  3.26
29        [spaghetti, nan, cooking oil, ground beef]  0.005  0.571  3.28
30  [spaghetti, nan, frozen vegetables, ground beef]  0.009  0.311  3.17
31         [nan, frozen vegetables, milk, olive oil]  0.005  0.203  3.09
32   [mineral water, nan, frozen vegetables, shrimp]  0.007  0.305  3.20
33    [spaghetti, nan, frozen vegetables, olive oil]  0.006  0.206  3.13
34       [spaghetti, nan, frozen vegetables, shrimp]  0.006  0.215  3.02
35     [spaghetti, tomatoes, nan, frozen vegetables]  0.007  0.239  3.50
36      [spaghetti, nan, ground beef, grated cheese]  0.005  0.323  3.28
37  [herb & pepper, mineral water, nan, ground beef]  0.007  0.391  3.98
38      [herb & pepper, nan, spaghetti, ground beef]  0.006  0.393  4.00
39               [olive oil, nan, milk, ground beef]  0.005  0.224  3.41
40             [spaghetti, nan, shrimp, ground beef]  0.006  0.523  3.01
41                 [spaghetti, nan, milk, olive oil]  0.007  0.203  3.09
42             [soup, mineral water, nan, olive oil]  0.005  0.225  3.43
43             [spaghetti, nan, pancakes, olive oil]  0.005  0.201  3.06

In [22]:
df_results.columns = ["Product_Associations","Support","Confidence","Lift"]
df_results.head()

               Product_Associations  Support  Confidence  Lift
0  [escalope, mushroom cream sauce]    0.006       0.301  3.79
1                 [escalope, pasta]    0.006       0.373  4.70
2      [herb & pepper, ground beef]    0.016       0.323  3.29
3       [tomato sauce, ground beef]    0.005       0.377  3.84
4    [whole wheat pasta, olive oil]    0.008       0.271  4.12

In [23]:
df_results.to_csv("Product_Association.csv",index=False)