<a href="https://colab.research.google.com/github/RadhikaNir/Machine-Learning-1633/blob/main/PCA_Principal_Component_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Principal component Analysis -> A technique used to eliminate curse of Dimensinality

In [1]:
import pandas as pd
df = pd.read_csv(r"https://raw.githubusercontent.com/RadhikaNir/Datasets/refs/heads/main/Cars93.csv")
df.head()

,id,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,1,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,...,5,177,102,68,37,26.5,11.0,2705,non-USA,Acura Integra
1,2,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,...,5,195,115,71,38,30.0,15.0,3560,non-USA,Acura Legend
2,3,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,...,5,180,102,67,37,28.0,14.0,3375,non-USA,Audi 90
3,4,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,...,6,193,106,70,37,31.0,17.0,3405,non-USA,Audi 100
4,5,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,...,4,186,109,69,39,27.0,13.0,3640,non-USA,BMW 535i

## Perform Basic data quality checks

In [2]:
df.shape

(93, 28)

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 28 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  93 non-null     int64
 1   Manufacturer        93 non-null     object
 2   Model               93 non-null     object
 3   Type                93 non-null     object
 4   Min.Price           93 non-null     float64
 5   Price               93 non-null     float64
 6   Max.Price           93 non-null     float64
 7   MPG.city            93 non-null     int64
 8   MPG.highway         93 non-null     int64
 9   AirBags             56 non-null     object
 10  DriveTrain          93 non-null     object
 11  Cylinders           93 non-null     object
 12  EngineSize          93 non-null     float64
 13  Horsepower          93 non-null     int64
 14  RPM                 93 non-null     int64
 15  Rev.per.mile        93 non-null     int64
 16  Man.trans.avail     93 non-null     object
 17  Fuel.tank.capacity  93 non-null     float64
 18  Passengers          93 non-null     int64
 19  Length              93 non-null     int64
 20  Wheelbase           93 non-null     int64
 21  Width               93 non-null     int64
 22  Turn.circle         93 non-null     int64
 23  Rear.seat.room      91 non-null     float64
 24  Luggage.room        82 non-null     float64
 25  Weight              93 non-null     int64
 26  Origin              93 non-null     object
 27  Make                93 non-null     object
dtypes: float64(7), int64(12), object(9)
memory usage: 20.5+ KB

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.isna().sum()

id                     0
Manufacturer           0
Model                  0
Type                   0
Min.Price              0
Price                  0
Max.Price              0
MPG.city               0
MPG.highway            0
AirBags               37
DriveTrain             0
Cylinders              0
EngineSize             0
Horsepower             0
RPM                    0
Rev.per.mile           0
Man.trans.avail        0
Fuel.tank.capacity     0
Passengers             0
Length                 0
Wheelbase              0
Width                  0
Turn.circle            0
Rear.seat.room         2
Luggage.room          11
Weight                 0
Origin                 0
Make                   0
dtype: int64

## Seaparte X and Y features

In [6]:
X = df.drop(columns=['id','Weight'])
Y = df[['Weight']]

In [7]:
X.head()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Fuel.tank.capacity,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Origin,Make
0,Acura,Integra,Small,12.9,15.9,18.8,25,31,NaN,Front,...,13.2,5,177,102,68,37,26.5,11.0,non-USA,Acura Integra
1,Acura,Legend,Midsize,29.2,33.9,38.7,18,25,Driver & Passenger,Front,...,18.0,5,195,115,71,38,30.0,15.0,non-USA,Acura Legend
2,Audi,90,Compact,25.9,29.1,32.3,20,26,Driver only,Front,...,16.9,5,180,102,67,37,28.0,14.0,non-USA,Audi 90
3,Audi,100,Midsize,30.8,37.7,44.6,19,26,NaN,Front,...,21.1,6,193,106,70,37,31.0,17.0,non-USA,Audi 100
4,BMW,535i,Midsize,23.7,30.0,36.2,22,30,Driver only,Rear,...,21.1,4,186,109,69,39,27.0,13.0,non-USA,BMW 535i

In [8]:
Y.head()

   Weight
0    2705
1    3560
2    3375
3    3405
4    3640

In [9]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,random_state=21,train_size=0.85)

In [10]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import  SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,OneHotEncoder

cat = list(X.select_dtypes(include='object'))
con = list(X.select_dtypes(include='number'))

num_pipe = make_pipeline(SimpleImputer(strategy='median'),StandardScaler())

cat_pipe = make_pipeline(SimpleImputer(strategy='most_frequent'),OneHotEncoder(handle_unknown='ignore',sparse_output=False))

pre = ColumnTransformer([
    ('cat',cat_pipe,cat),
    ('con',num_pipe,con)
]).set_output(transform='pandas')
pre

ColumnTransformer(transformers=[('cat',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['Manufacturer', 'Model', 'Type', 'AirBags',
                                  'DriveTrain', 'Cylinders', 'Man.trans.avail',
                                  'Origin', 'Make']),
                                ('con',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('standardscaler',
                                                  StandardScaler())]),
                                 ['Min.Price', 'Price', 'Max.Price', 'MPG.city',
                                  'MPG.highway', 'EngineSize', 'Horsepower',
                                  'RPM', 'Rev.per.mile', 'Fuel.tank.capacity',
                                  'Passengers', 'Length', 'Wheelbase', 'Width',
                                  'Turn.circle', 'Rear.seat.room',
                                  'Luggage.room'])])

In [11]:
pre.fit(xtrain)

ColumnTransformer(transformers=[('cat',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehotencoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['Manufacturer', 'Model', 'Type', 'AirBags',
                                  'DriveTrain', 'Cylinders', 'Man.trans.avail',
                                  'Origin', 'Make']),
                                ('con',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='median')),
                                                 ('standardscaler',
                                                  StandardScaler())]),
                                 ['Min.Price', 'Price', 'Max.Price', 'MPG.city',
                                  'MPG.highway', 'EngineSize', 'Horsepower',
                                  'RPM', 'Rev.per.mile', 'Fuel.tank.capacity',
                                  'Passengers', 'Length', 'Wheelbase', 'Width',
                                  'Turn.circle', 'Rear.seat.room',
                                  'Luggage.room'])])

In [12]:
xtrain_pre = pre.transform(xtrain)
xtest_pre = pre.transform(xtest)

In [13]:
xtrain_pre.shape[1]

227

## PCA Components

In [14]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
pca.fit(xtrain_pre)

PCA(n_components=3)

In [15]:
xtrain_pca = pca.transform(xtrain_pre)
xtrain_pca

array([[-4.23429284, -0.41263931,  0.68971844],
       [-1.69607731,  1.093705  , -1.1491311 ],
       [ 2.73439289, -1.42577296,  0.74614804],
       [ 1.61729423, -0.85077649, -0.34466649],
       [-5.01090695, -0.34115157,  0.15823895],
       [-0.34904693,  2.35722057,  0.14038747],
       [-2.68432389, -0.20783848,  0.1629461 ],
       [ 2.25063322,  1.51155208,  0.29662947],
       [ 2.9150422 , -0.61373618,  0.76858755],
       [ 6.7551621 , -0.09963616,  1.08711369],
       [ 1.96857783,  4.21936519, -0.63233282],
       [ 5.44134608, -1.98167505, -0.4496787 ],
       [ 0.69651462, -1.61753437,  0.73798566],
       [-4.17025696,  0.36642881, -0.34444913],
       [ 0.18803641, -1.15540369,  0.34624395],
       [-1.97553001, -0.6917003 , -0.55165363],
       [-2.33661394,  0.20945885, -2.41172265],
       [-0.33885932, -1.79485952,  0.32941301],
       [-0.71919933, -0.03140343,  1.03847391],
       [ 3.01022999,  0.24660459, -1.08175556],
       [ 2.68657277, -1.19480903, -0.18679355],
       [ 6.76745457, -2.0029564 , -0.67411703],
       [ 0.70751366,  1.96996138,  0.48385755],
       [-0.99647334,  0.67310443,  0.32009764],
       [-0.6661061 ,  0.48606232,  0.68650075],
       [ 2.13122317, -0.4540204 , -0.64564007],
       [ 4.33866956,  5.98868183,  1.57565391],
       [-1.21403388, -1.59147058, -1.04767714],
       [ 2.46970618, -1.27087888, -0.97109698],
       [-7.37685136, -0.24885691,  1.9163114 ],
       [ 5.7494597 ,  4.44065213,  1.06906467],
       [-0.20817461, -0.32989955,  0.98177841],
       [-5.73468068, -0.60890151, -0.70995511],
       [-0.65041798, -0.04163007,  0.43100182],
       [-0.70654194,  0.62685185,  1.85054657],
       [ 1.47371361,  0.33772441,  0.01893859],
       [-4.4680961 , -0.50291854,  0.07145931],
       [-3.67780359, -0.86292925,  0.23660714],
       [-0.78321472, -0.49533171,  0.46801727],
       [-2.45600976,  0.77673697,  0.78754107],
       [-4.57215825,  0.60141424, -1.24704415],
       [ 5.28775558, -3.04841752, -0.39979167],
       [ 6.00839282, -0.49392618,  0.89447262],
       [-3.36169759, -0.32581288,  0.14996088],
       [ 0.8560922 , -1.98955094,  0.57775889],
       [-2.3899427 , -1.51983366, -0.57850245],
       [ 3.58822082, -1.53614273,  0.03492417],
       [ 3.27596913, -2.07570604, -0.65810216],
       [ 1.01689862,  1.79107346,  1.67902309],
       [ 3.77892032, -1.8040081 , -0.36800729],
       [-1.59662944, -1.13116241, -0.25457825],
       [-1.10551211, -0.05818499, -2.44864067],
       [-4.42864807,  0.17402673, -0.53274062],
       [-0.02502131,  0.07212598,  0.6804605 ],
       [-2.93823168, -0.37912761,  0.29542424],
       [-2.88946081, -0.50338697,  0.76496495],
       [-0.40544084,  2.19592989,  1.03029944],
       [ 4.71638823,  0.04692149,  0.56325649],
       [ 3.66395338, -1.6351405 ,  0.25353655],
       [ 4.06377592,  4.16289503, -2.99644043],
       [ 0.18422762, -1.48271119,  0.60399468],
       [-4.46397497, -0.23295729,  1.72300514],
       [-0.43622878,  2.4107094 , -0.61984214],
       [ 3.58387811, -0.9923958 ,  0.08120798],
       [ 0.6921387 , -1.40082743,  0.29833898],
       [-4.01321412,  1.3996322 , -3.167227  ],
       [ 2.1348833 , -1.58674614,  1.88869876],
       [-3.57844187, -0.19729823,  0.31703777],
       [-2.78165378, -0.06453725,  0.49637046],
       [-3.67502876,  0.23461653,  0.49992559],
       [-3.99901489, -0.94122035,  0.75161257],
       [ 1.44754638, -0.04385558, -2.94322384],
       [ 2.56930259, -1.76638331, -1.60807154],
       [ 3.34894387, -1.59334261, -0.49038164],
       [ 1.79495613,  1.64181296, -0.08965362],
       [ 1.33767087,  2.7493705 ,  0.34902175],
       [ 0.33709163,  5.07996445, -0.40881151],
       [-6.54120316,  0.62549787, -0.57933079],
       [-1.93353435, -0.85869506, -0.74149808]])

In [16]:
pca.explained_variance_

array([10.93073628,  2.95185393,  1.11589207])

In [17]:
pca.feature_names_in_

array(['cat__Manufacturer_Acura', 'cat__Manufacturer_Audi',
       'cat__Manufacturer_BMW', 'cat__Manufacturer_Buick',
       'cat__Manufacturer_Cadillac', 'cat__Manufacturer_Chevrolet',
       'cat__Manufacturer_Chrylser', 'cat__Manufacturer_Chrysler',
       'cat__Manufacturer_Dodge', 'cat__Manufacturer_Eagle',
       'cat__Manufacturer_Ford', 'cat__Manufacturer_Geo',
       'cat__Manufacturer_Honda', 'cat__Manufacturer_Hyundai',
       'cat__Manufacturer_Infiniti', 'cat__Manufacturer_Lexus',
       'cat__Manufacturer_Lincoln', 'cat__Manufacturer_Mazda',
       'cat__Manufacturer_Mercedes-Benz', 'cat__Manufacturer_Mercury',
       'cat__Manufacturer_Mitsubishi', 'cat__Manufacturer_Nissan',
       'cat__Manufacturer_Oldsmobile', 'cat__Manufacturer_Plymouth',
       'cat__Manufacturer_Pontiac', 'cat__Manufacturer_Saab',
       'cat__Manufacturer_Saturn', 'cat__Manufacturer_Subaru',
       'cat__Manufacturer_Toyota', 'cat__Manufacturer_Volkswagen',
       'cat__Manufacturer_Volvo', 'cat__Model_190E', 'cat__Model_300E',
       'cat__Model_323', 'cat__Model_535i', 'cat__Model_626',
       'cat__Model_850', 'cat__Model_90', 'cat__Model_900',
       'cat__Model_Accord', 'cat__Model_Achieva', 'cat__Model_Aerostar',
       'cat__Model_Altima', 'cat__Model_Astro', 'cat__Model_Bonneville',
       'cat__Model_Camry', 'cat__Model_Capri', 'cat__Model_Caravan',
       'cat__Model_Cavalier', 'cat__Model_Celica', 'cat__Model_Century',
       'cat__Model_Civic', 'cat__Model_Colt', 'cat__Model_Concorde',
       'cat__Model_Continental', 'cat__Model_Corrado',
       'cat__Model_Corsica', 'cat__Model_Corvette', 'cat__Model_Cougar',
       'cat__Model_Crown_Victoria', 'cat__Model_Cutlass_Ciera',
       'cat__Model_DeVille', 'cat__Model_Diamante', 'cat__Model_Dynasty',
       'cat__Model_ES300', 'cat__Model_Eighty-Eight',
       'cat__Model_Elantra', 'cat__Model_Escort', 'cat__Model_Eurovan',
       'cat__Model_Excel', 'cat__Model_Festiva', 'cat__Model_Firebird',
       'cat__Model_Fox', 'cat__Model_Grand_Prix', 'cat__Model_Integra',
       'cat__Model_Justy', 'cat__Model_Laser', 'cat__Model_LeBaron',
       'cat__Model_LeMans', 'cat__Model_LeSabre', 'cat__Model_Legacy',
       'cat__Model_Loyale', 'cat__Model_Lumina', 'cat__Model_Lumina_APV',
       'cat__Model_Maxima', 'cat__Model_Metro', 'cat__Model_Mirage',
       'cat__Model_Mustang', 'cat__Model_Passat', 'cat__Model_Protege',
       'cat__Model_Q45', 'cat__Model_Quest', 'cat__Model_RX-7',
       'cat__Model_Riviera', 'cat__Model_Roadmaster', 'cat__Model_SC300',
       'cat__Model_SL', 'cat__Model_Scoupe', 'cat__Model_Sentra',
       'cat__Model_Silhouette', 'cat__Model_Sonata', 'cat__Model_Spirit',
       'cat__Model_Storm', 'cat__Model_Summit', 'cat__Model_Sunbird',
       'cat__Model_Taurus', 'cat__Model_Tempo', 'cat__Model_Tercel',
       'cat__Model_Town_Car', 'cat__Model_Vision', 'cat__Type_Compact',
       'cat__Type_Large', 'cat__Type_Midsize', 'cat__Type_Small',
       'cat__Type_Sporty', 'cat__Type_Van',
       'cat__AirBags_Driver & Passenger', 'cat__AirBags_Driver only',
       'cat__DriveTrain_4WD', 'cat__DriveTrain_Front',
       'cat__DriveTrain_Rear', 'cat__Cylinders_3', 'cat__Cylinders_4',
       'cat__Cylinders_5', 'cat__Cylinders_6', 'cat__Cylinders_8',
       'cat__Cylinders_rotary', 'cat__Man.trans.avail_No',
       'cat__Man.trans.avail_Yes', 'cat__Origin_USA',
       'cat__Origin_non-USA', 'cat__Make_Acura Integra',
       'cat__Make_Audi 90', 'cat__Make_BMW 535i',
       'cat__Make_Buick Century', 'cat__Make_Buick LeSabre',
       'cat__Make_Buick Riviera', 'cat__Make_Buick Roadmaster',
       'cat__Make_Cadillac DeVille', 'cat__Make_Chevrolet Astro',
       'cat__Make_Chevrolet Cavalier', 'cat__Make_Chevrolet Corsica',
       'cat__Make_Chevrolet Corvette', 'cat__Make_Chevrolet Lumina',
       'cat__Make_Chevrolet Lumina_APV', 'cat__Make_Chrylser Concorde',
       'cat__Make_Chrysler LeBaron', 'cat__Make_Dodge Caravan',
       'cat__Make_Dodge Colt', 'cat__Make_Dodge Dynasty',
       'cat__Make_Dodge Spirit', 'cat__Make_Eagle Summit',
       'cat__Make_Eagle Vision', 'cat__Make_Ford Aerostar',
       'cat__Make_Ford Crown_Victoria', 'cat__Make_Ford Escort',
       'cat__Make_Ford Festiva', 'cat__Make_Ford Mustang',
       'cat__Make_Ford Taurus', 'cat__Make_Ford Tempo',
       'cat__Make_Geo Metro', 'cat__Make_Geo Storm',
       'cat__Make_Honda Accord', 'cat__Make_Honda Civic',
       'cat__Make_Hyundai Elantra', 'cat__Make_Hyundai Excel',
       'cat__Make_Hyundai Scoupe', 'cat__Make_Hyundai Sonata',
       'cat__Make_Infiniti Q45', 'cat__Make_Lexus ES300',
       'cat__Make_Lexus SC300', 'cat__Make_Lincoln Continental',
       'cat__Make_Lincoln Town_Car', 'cat__Make_Mazda 323',
       'cat__Make_Mazda 626', 'cat__Make_Mazda Protege',
       'cat__Make_Mazda RX-7', 'cat__Make_Mercedes-Benz 190E',
       'cat__Make_Mercedes-Benz 300E', 'cat__Make_Mercury Capri',
       'cat__Make_Mercury Cougar', 'cat__Make_Mitsubishi Diamante',
       'cat__Make_Mitsubishi Mirage', 'cat__Make_Nissan Altima',
       'cat__Make_Nissan Maxima', 'cat__Make_Nissan Quest',
       'cat__Make_Nissan Sentra', 'cat__Make_Oldsmobile Achieva',
       'cat__Make_Oldsmobile Cutlass_Ciera',
       'cat__Make_Oldsmobile Eighty-Eight',
       'cat__Make_Oldsmobile Silhouette', 'cat__Make_Plymouth Laser',
       'cat__Make_Pontiac Bonneville', 'cat__Make_Pontiac Firebird',
       'cat__Make_Pontiac Grand_Prix', 'cat__Make_Pontiac LeMans',
       'cat__Make_Pontiac Sunbird', 'cat__Make_Saab 900',
       'cat__Make_Saturn SL', 'cat__Make_Subaru Justy',
       'cat__Make_Subaru Legacy', 'cat__Make_Subaru Loyale',
       'cat__Make_Toyota Camry', 'cat__Make_Toyota Celica',
       'cat__Make_Toyota Tercel', 'cat__Make_Volkswagen Corrado',
       'cat__Make_Volkswagen Eurovan', 'cat__Make_Volkswagen Fox',
       'cat__Make_Volkswagen Passat', 'cat__Make_Volvo 850',
       'con__Min.Price', 'con__Price', 'con__Max.Price', 'con__MPG.city',
       'con__MPG.highway', 'con__EngineSize', 'con__Horsepower',
       'con__RPM', 'con__Rev.per.mile', 'con__Fuel.tank.capacity',
       'con__Passengers', 'con__Length', 'con__Wheelbase', 'con__Width',
       'con__Turn.circle', 'con__Rear.seat.room', 'con__Luggage.room'],
      dtype=object)

In [18]:
len(pca.feature_names_in_)

227

## Converting array into dataframe

In [19]:
X_pca = pd.DataFrame(xtrain_pca)
X_pca

           0         1         2
0  -4.234293 -0.412639  0.689718
1  -1.696077  1.093705 -1.149131
2   2.734393 -1.425773  0.746148
3   1.617294 -0.850776 -0.344666
4  -5.010907 -0.341152  0.158239
..       ...       ...       ...
74  1.794956  1.641813 -0.089654
75  1.337671  2.749371  0.349022
76  0.337092  5.079964 -0.408812
77 -6.541203  0.625498 -0.579331
78 -1.933534 -0.858695 -0.741498

[79 rows x 3 columns]

In [20]:
X_pca.columns = ['PC1','PC2','PC3']
X_pca

         PC1       PC2       PC3
0  -4.234293 -0.412639  0.689718
1  -1.696077  1.093705 -1.149131
2   2.734393 -1.425773  0.746148
3   1.617294 -0.850776 -0.344666
4  -5.010907 -0.341152  0.158239
..       ...       ...       ...
74  1.794956  1.641813 -0.089654
75  1.337671  2.749371  0.349022
76  0.337092  5.079964 -0.408812
77 -6.541203  0.625498 -0.579331
78 -1.933534 -0.858695 -0.741498

[79 rows x 3 columns]

In [21]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=50,
                              max_depth=5)
model.fit(X_pca,ytrain['Weight'])

RandomForestRegressor(max_depth=5, n_estimators=50)

In [23]:
model.score(X_pca,ytrain)

0.9829240900616998

In [25]:
Xtest_pca = pca.transform(xtest_pre)
Xtest_pca

array([[-2.11912396, -1.14247165, -0.87561442],
       [ 2.39929463, -0.97503453,  1.82644713],
       [-0.01518277,  0.69963739,  0.68119721],
       [ 3.88452939, -0.92764279,  1.5613258 ],
       [ 5.4856604 , -2.17490347, -0.62644211],
       [-6.24242883,  0.06318754,  1.31916202],
       [-1.25642525, -0.17685258, -1.07626002],
       [ 1.0634637 ,  3.32755831, -2.97977578],
       [ 5.45370213,  2.84425779,  0.83080941],
       [-1.84127173,  1.92820538, -1.00943389],
       [ 1.17216339, -0.28759617, -2.97292011],
       [ 2.78364244,  2.07805161,  2.21867806],
       [ 2.1307847 , -0.82491378,  0.09289096],
       [ 2.93948907,  2.08849984,  1.39928795]])

In [26]:
Xtest_pca = pd.DataFrame(Xtest_pca)
Xtest_pca.columns = ['PC1','PC2','PC3']

In [27]:
model.score(Xtest_pca,ytest)

0.922181244111601